# Generated by Django 5.2.3 on 2025-06-19 23:47

import django.core.validators
import django.db.models.deletion
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('CPF', models.CharField(max_length=11)),
                ('data_de_nascimento', models.DateField()),
                ('telefone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('email', models.EmailField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('ementa', models.TextField()),
                ('carga_horaria', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Carga Horária')),
                ('email', models.EmailField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('data_de_nascimento', models.DateField()),
                ('formacao', models.CharField(max_length=50, verbose_name='Formação')),
                ('matricula', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Disciplina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('carga_horaria', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Carga Horária')),
                ('ementa', models.TextField()),
                ('programacao', models.TextField(verbose_name='Programação')),
                ('avaliacao', models.DecimalField(decimal_places=2, max_digits=4, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(10.0)], verbose_name='Avaliação')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestao_escolar.curso')),
                ('coordenador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestao_escolar.professor')),
            ],
        ),
        migrations.AddField(
            model_name='curso',
            name='coordenador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestao_escolar.professor'),
        ),
        migrations.CreateModel(
            name='Turma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=50)),
                ('data_inicial', models.DateField()),
                ('data_final', models.DateField()),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestao_escolar.curso')),
            ],
        ),
        migrations.CreateModel(
            name='Matricula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modalidade_de_ensino', models.CharField(max_length=50)),
                ('data_de_matricula', models.DateField()),
                ('status', models.CharField(choices=[('ativa', 'Ativa'), ('trancada', 'Trancada'), ('cancelada', 'Cancelada'), ('concluida', 'Concluída')], max_length=20)),
                ('nota_final', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(10.0)])),
                ('observacoes', models.TextField(verbose_name='Observações')),
                ('frequencia_final', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)])),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestao_escolar.aluno')),
                ('turma', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestao_escolar.turma')),
            ],
        ),
        migrations.CreateModel(
            name='Frequencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('presenca', models.BooleanField(verbose_name='Presença')),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestao_escolar.aluno')),
                ('disciplina', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestao_escolar.disciplina')),
                ('turma', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestao_escolar.turma')),
            ],
        ),
    ]
