# Generated by Django 5.2.3 on 2025-06-19 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestao_escolar', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='matricula',
            old_name='nome',
            new_name='modalidade_de_ensino',
        ),
    ]
