# Generated by Django 5.2.3 on 2025-06-20 00:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao_escolar', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='CPF',
            field=models.CharField(max_length=14),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='telefone',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='Informe um telefone válido no formato (47) 98888-7777 ou 47988887777.', regex='^\\(?\\d{2}\\)? ?\\d{4,5}-?\\d{4}$')]),
        ),
    ]
