# Generated by Django 5.2.3 on 2025-06-20 01:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao_escolar', '0002_alter_aluno_cpf_alter_aluno_telefone'),
    ]

    operations = [
        migrations.AddField(
            model_name='disciplina',
            name='professor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='disciplinas_ministradas', to='gestao_escolar.professor'),
        ),
        migrations.AlterField(
            model_name='disciplina',
            name='coordenador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='disciplinas_coordenadas', to='gestao_escolar.professor'),
        ),
    ]
