# Generated by Django 5.2.3 on 2025-06-16 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao_escolar', '0005_aluno_curso_disciplina_frequencia_turma'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='ementa',
            field=models.CharField(default='Ementa não definida', max_length=1000),
            preserve_default=False,
        ),
    ]
