# Generated by Django 5.2.3 on 2025-06-16 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao_escolar', '0006_curso_ementa'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='carga_horaria',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='curso',
            name='coordenador_curso',
            field=models.CharField(default='N/A', max_length=50),
        ),
        migrations.AddField(
            model_name='curso',
            name='email_curso',
            field=models.CharField(default='noemail@domain.com', max_length=50),
        ),
        migrations.AlterField(
            model_name='curso',
            name='ementa',
            field=models.CharField(max_length=2000),
        ),
    ]
