# Generated by Django 5.2.3 on 2025-06-19 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao_escolar', '0007_curso_carga_horaria_curso_coordenador_curso_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='turma',
            old_name='nome',
            new_name='email_da_turma',
        ),
        migrations.RemoveField(
            model_name='curso',
            name='coordenador_curso',
        ),
        migrations.RemoveField(
            model_name='curso',
            name='email_curso',
        ),
        migrations.AddField(
            model_name='aluno',
            name='CPF',
            field=models.CharField(default='00000000000', max_length=11),
        ),
        migrations.AddField(
            model_name='curso',
            name='coordenador',
            field=models.CharField(default='Coordenador Padrão', max_length=50),
        ),
        migrations.AddField(
            model_name='curso',
            name='email',
            field=models.EmailField(default='admin@admin.com', max_length=50),
        ),
        migrations.AddField(
            model_name='professor',
            name='data_de_nascimento',
            field=models.DateField(default='2000-01-01'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='professor',
            name='email',
            field=models.CharField(default='admin@admin.com', max_length=50),
        ),
        migrations.AddField(
            model_name='professor',
            name='formacao',
            field=models.CharField(default='sem formação', max_length=50, verbose_name='Formação'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='professor',
            name='matricula',
            field=models.CharField(default='0000', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='curso',
            name='carga_horaria',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Carga Horária'),
        ),
    ]
