# Generated by Django 5.2.3 on 2025-06-19 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao_escolar', '0008_rename_nome_turma_email_da_turma_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='data_de_nascimento',
            field=models.DateField(default='2000-01-01'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='aluno',
            name='CPF',
            field=models.CharField(max_length=11),
        ),
        migrations.AlterField(
            model_name='curso',
            name='coordenador',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='curso',
            name='email',
            field=models.EmailField(max_length=50),
        ),
        migrations.AlterField(
            model_name='professor',
            name='email',
            field=models.CharField(max_length=50),
        ),
    ]
