# Generated by Django 5.2.3 on 2025-06-19 15:26

import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestao_escolar', '0009_aluno_data_de_nascimento_alter_aluno_cpf_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='telefone',
            field=phonenumber_field.modelfields.PhoneNumberField(default='00000000000', max_length=128, region=None),
            preserve_default=False,
        ),
    ]
