# Generated by Django 5.2.3 on 2025-06-19 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao_escolar', '0010_aluno_telefone'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='email',
            field=models.CharField(default='sememail@ifc.edu.br', max_length=50),
            preserve_default=False,
        ),
    ]
