# Generated by Django 5.2.3 on 2025-06-19 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao_escolar', '0011_aluno_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='disciplina',
            name='carga_horaria',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Carga Horária'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='disciplina',
            name='ementa',
            field=models.TextField(default='sem ementa'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='disciplina',
            name='programacao',
            field=models.TextField(default='Sem programação definida'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='curso',
            name='ementa',
            field=models.TextField(),
        ),
    ]
