# Generated by Django 5.2.3 on 2025-06-19 16:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao_escolar', '0012_disciplina_carga_horaria_disciplina_ementa_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='disciplina',
            name='avaliacao',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(10.0)], verbose_name='Avaliação'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='disciplina',
            name='programacao',
            field=models.TextField(verbose_name='Programação'),
        ),
    ]
